### ISSUE TITLE
Lua error in LFR raid...

### ISSUE THREAD

**Issue by Milky063** [BigWigsMods/BigWigs_Voice#37] opened 2023-02-20 22:23 UTC
got this lua error today....

1x BigWigs_Voice/Core.lua:20: script ran too long
[string "@BigWigs_Voice/Core.lua"]:20: in function <BigWigs_Voice/Core.lua:18>
[string "=[C]"]: ?
[string "@BigWigs/Loader.lua"]:1081: in function `SendMessage'
[string "@BigWigs_Core/BossPrototype.lua"]:2898: in function `PlaySound'
[string "@BigWigs_VaultOfTheIncarnates/SennarthTheColdBreath.lua"]:336: in function `?'
[string "@BigWigs_Core/BossPrototype.lua"]:589: in function <BigWigs_Core/BossPrototype.lua:555>

Locals:
Skipped (In Encounter)

**Comment by funkydude** [comment] 2023-02-20 22:38
This issue is also a duplicate of your issue here: https://github.com/BigWigsMods/LittleWigs/issues/882

**Closed as not planned by funkydude** 2023-02-20 22:38 UTC
