### ISSUE TITLE
Voice lines not working

### ISSUE THREAD

**Issue by Erythros** [BigWigsMods/BigWigs_Voice#29] opened 2020-12-15 20:07 UTC
Not sure if this is an issue or just some misconfiguration on my side. Installed BW and the voice pack. Went in BW, selected a boss and a voice. Like this.
![image](https://user-images.githubusercontent.com/2624183/102266831-a898f800-3f21-11eb-879e-0ee1543f5533.png)

Voice is obviously checked.
![image](https://user-images.githubusercontent.com/2624183/102266890-b9496e00-3f21-11eb-908d-92dd87e0a723.png)

The problem: it doesn't do anything. Doesn't play the voice, but it does show the text. Just the countdown works

**Comment by sehra** [comment] 2020-12-16 15:13
Check if the file `(WoW directory)\_retail_\Interface\AddOns\BigWigs_Voice\Sounds\330711.ogg` is present.

There was an earlier issue with missing sounds so thinking it might be related to package managers.

**Comment by Erythros** [comment] 2020-12-16 15:20
> Check if the file `(WoW directory)\_retail_\Interface\AddOns\BigWigs_Voice\Sounds\330711.ogg` is present.
> 
> There was an earlier issue with missing sounds so thinking it might be related to package managers.

Thank you for your input.
It's there. Together with 2477 other files.
![image](https://user-images.githubusercontent.com/2624183/102367885-ee59cd00-3fc2-11eb-943a-b065eba7dcbe.png)

**Comment by sehra** [comment] 2020-12-16 19:29
Just did Shriekwing, sound worked fine with latest version (9.0.2.2).

**Comment by Erythros** [comment] 2020-12-16 21:27
> Just did Shriekwing, sound worked fine with latest version (9.0.2.2).

I am on 9.0.2.3.

Can it be related to the sounds? LIke to work only with some sounds? Not sure what else to test.

**Comment by sehra** [comment] 2020-12-17 23:00
Oh right I meant 9.0.2.3. You can try playing the sound and see if it works.
`/script PlaySoundFile("Interface\\AddOns\\BigWigs_Voice\\Sounds\\330711.ogg", "Master")`

**Comment by Erythros** [comment] 2020-12-18 12:12
That _does_ work.
It also works inside BW, under sounds. If I go, select a sound (I really like this one with "run away little girl") and I click on the voice button, it plays well.  E.g.
![image](https://user-images.githubusercontent.com/2624183/102613293-e755ca80-413a-11eb-85aa-50bb40a756af.png)

But then I select that one (with run away little girl) and nothing happens in the raid. I just see the cast / colors and the cooldown.

Can the problem be with the sound? 

Guess I could also uninstall BigWigs, LittleWigs and the entire voice pack, and then re-install to see if that works...

**Comment by funkydude** [comment] 2020-12-18 12:44
Ofcourse it doesn't work. You have the voice pack installed, which overwrites BigWigs sounds.

You can't have both.
Either uninstall the voice pack if you want BigWigs sounds like "run away" to play, or disable the "voice" checkbox for the specific abilities that you want a BigWigs sound to play e.g. Earsplitting Shriek above

**Comment by Erythros** [comment] 2020-12-18 12:50
Oh? So I can't overwrite the default "voice" with a custom one from BW?
As in, most of the times I want the lines from the "voice pack", but sometimes I like to make it really obvious and select something else.

**Comment by funkydude** [comment] 2020-12-18 12:52
Yes you can, you can see the option in your screenshot from the first post:
![image](https://user-images.githubusercontent.com/16833/102616675-d18ed800-412f-11eb-9a0d-fae6ae72c4db.png)

**Comment by Erythros** [comment] 2020-12-18 18:23
> Yes you can, you can see the option in your screenshot from the first post:

Let me see if I got this:

- If `Voice` is active, it doesn't matter what manual BW voiceline I select, it will use the default from the voice_pack
- If "Voice" is deselected, BW will play any sound manually linked (like the one with "run away little girl".

Is this correct?

Edit: still not working.

**Comment by blub0r** [comment] 2020-12-20 16:27
I dont know ... i switched from DBM to BW, reinstalled all new, but i still have the same problem. BW and BW voice installed, and it should work but nothing happens in raid. Good to know that im not the only one. i checked stuff with other players and all have the same configuration out of the box.

**Comment by sehra** [comment] 2020-12-20 22:59
Could check how many sound channels you have under System/Sounds. There is not much to go on here, try BugSack if it captures anything.

**Comment by funkydude** [comment] 2021-05-13 22:15
Closing. Works fine for virtually everyone. The cause behind the issue being described here is unlikely to be discovered.

**Closed as completed by funkydude** 2021-05-13 22:15 UTC
