### ISSUE TITLE
button to turn off per boss /trash

### ISSUE THREAD

**Issue by G1ak1** [BigWigsMods/BigWigs_Voice#41] opened 2024-08-28 22:04 UTC
hey guys. this ie very helpful but also kinda spammy. i am using it for a long time but i dont really want it to tell me eeevry spell on every trash mobs pull we do etc. same on bosses. can an option be added to turn it off completely and then tick the option to turn it on (that already exists per ability) on the abilities that we want to hear???

thank u

**Comment by funkydude** [comment] 2024-08-28 22:41
Thanks for the suggestion, but it's a duplicate of #34

**Closed as completed by funkydude** 2024-08-28 22:41 UTC
